---
image: debian:testing

stages:
  - build

before_script:
  - apt update
  - apt-get install --no-install-recommends -y gcc-7 g++-7 libwebsocketpp-dev cmake libboost-system-dev libyaml-cpp-dev libssl-dev git-core libluajit-5.1-dev make
  - git submodule init
  - git submodule update

compile:
  stage: build
  script:
    - CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 cmake  .
    - make
    - cpack -G DEB && dpkg -i lightsd-*.deb && whereis lightsd
