---
image: debian:testing

stages:
  - build

cache:
  key: apt-cache
  paths:
  - apt-cache/

before_script:
  - sudo apt-get update -yq && sudo apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y foo

before_script:
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - apt update
  - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install --no-install-recommends -y gcc-7 g++-7 libwebsocketpp-dev cmake libboost-system-dev libyaml-cpp-dev libssl-dev git-core libluajit-5.1-dev make ca-certificates
  - git submodule init
  - git submodule update

compile:
  stage: build
  script:
    - CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 cmake  .
    - make VERBOSE=1 
    - cpack -G DEB && dpkg -i lightsd-*.deb && whereis lightsd
