---
image: debian:testing

stages:
  - build

before_script:
  - apt update
  - apt install -y gcc g++ libwebsocketpp-dev cmake libboost-system-dev libyaml-cpp-dev libssl-dev git-core libluajit-5.1-dev
  - git submodule init
  - git submodule update

compile:
  stage: build
  script: cmake . && make
