---
width: 1200
fps: 30

mqtt:
  broker: whisky.w17.io
  realm: w17/lounge/light/ 
  # username: the_user
  # password: my_s3cret_p4ssw0rd

operations:
  rainbow:
    type: rainbow
    params:
      enabled: true
  raindrop:
    type: raindrop
    params:
      enabled: true
      saturation_min: 0.1
      saturation_max: 0.8
      hue_min: 10
      hue_max: 320

      value_min: 0.1
      value_max: 0.7

      chance: 0.999
      decay_low: 0.9
      decay_high: 0.99
      decay_resolution: 100000
  splashdrop:
    type: splashdrop
    params:
      enabled: true
  gameoflife:
    type: gameoflife
    params:
      enabled: false
  udp-hsv-1337:
    type: hsvudpinput
    params:
      enabled: false
      port: 1337
  shade:
    type: shade
    params:
      value: 1
  bell:
    type: bell
    params:
      enabled: false
      duration: 5000
  rotate:
    type: rotate
    params:
      step_width: 50
  example-lua:
    type: lua
    params:
      filename: example.lua
  fade-100-left:
    type: fade
    params:
      min: 0.0
      max: 1.0
      from: 0
      to: 100
  sub-sequence1:
    type: sequence
    params:
      enabled: true
      from: 10
      to: 200
      operations:
        - name: raindrop
          type: raindrop
          params:
            enabled: true
        - name: rotate
          type: rotate
          params:
            enabled: true
            step_width: 10
  sub-sequence2:
    type: sequence
    params:
      enabled: true
      from: 200
      to: 400
      operations:
        - name: rainbow
          type: rainbow
          params:
            enabled: true
        - name: rotate
          type: rotate
          params:
            enabled: true
            step_width: -20
  sub-sequence3:
    type: sequence
    params:
      enabled: true
      from: 400
      to: 600
      operations:
        - name: bell
          type: bell
          params:
            enabled: true
            duration: 500000000
        - name: rotate
          type: rotate
          params:
            enabled: true
            step_width: 40




sequence:
  - rainbow
#  - raindrop
#  - splashdrop
  - gameoflife
#  - udp-hsv-1337
#  - example-lua
#  - fade-100-left
#  - example-lua
  - sub-sequence1
  - sub-sequence2
  - sub-sequence3
  - rotate
  - shade
  - bell

outputs:
  Websocket1:
    type: websocket
    params:
      port: 9000
  Ranzput:
    type: hsvudp
    params:
      host: 172.23.97.135
      port: 1337
