---
width: 2000
fps: 20

mqtt:
  broker: whisky.w17.io
  realm: /lightsbla/


operations:
  rainbow:
    type: initRainbow
    params:
      enabled: true
  raindrop:
    type: raindrop
    params:
      enabled: false
      saturation_min: 0.1
      saturation_max: 0.8
      hue_min: 10
      hue_max: 320

      value_min: 0.1
      value_max: 0.7

      chance: 0.999
      decay_low: 0.9
      decay_high: 0.99
      decay_resolution: 100000
  splashdrop:
    type: splashdrop
    params:
      enabled: false
  gameoflife:
    type: gameoflife
    params:
      enabled: false
  udp-hsv-1337:
    type: hsvudpinput
    params:
      enabled: false
      port: 1337
  shade:
    type: shade
    params:
      value: 1
  bell:
    type: bell
    params:
      enabled: false
      duration: 5000
  rotate:
    type: rotate
    params:
      step_width: 0
  example-lua:
    type: lua
    params:
      filename: example.lua
  fade-100-left:
    type: fade
    params:
      min: 0.0
      max: 1.0
      from: 0
      to: 100

sequence:
  - rainbow
  - raindrop
  - splashdrop
  - gameoflife
  - udp-hsv-1337
  - example-lua
  - fade-100-left
  - example-lua
  - rotate
  - shade
  - bell

outputs:
  Websocket1:
    type: websocket
    params:
      port: 9000
#  CrashMe:
#    type: devmem
#    params:
#      filename: /dev/mem
#      lengths:
#        - 1202
#        - 1000
#  SPI1:
#    type: spi
#    params:
#      device: /dev/spidev.0
#  SHM:
#    type: shm
#    params:
#      filename: leds

#  UDPOutput:
#    type: udp
#    params:
#      host: "fd42:ccc:da:1::2"
#      port: 6453

#output: Websocket1
