---
width: 1000
fps: 1

mqtt:
  broker: whisky.w17.io
  realm: /lights-foo/


sequence:
  - initRainbow
  - raindrop:
      saturation_min: 0.1
      saturation_max: 0.8
      hue_min: 10
      hue_max: 320

      value_min: 0.1
      value_max: 0.7

      chance: 0.999
      decay_low: 0.9
      decay_high: 0.99
      decay_resolution: 100000

  - splashdrop:
      enabled: false

  - gameoflife:
      enabled: true

#  - udpinput:
#      enabled: 0
#      port: 1337


#  - initSolidColor:
#      hue: 0.0
#      saturation: 0.0
#      value: 0.1

  - shade:
      value: 1

  - bell

  - rotate:
      step_width: 0
   
  - lua:
      enabled: false
      name: example
      filename: example.lua
#  - fade:
#      min: 0.0
#      max: 1
#      from: 0
#      to: 1200

#  - fade:
#      min: 1
#      max: 1
#      from: 35
#      to: 80


outputs:
  Websocket1:
    type: websocket
    params:
      port: 9000
  CrashMe:
    type: devmem
    params:
      filename: /dev/mem
#  SPI1:
#    type: spi
#    params:
#      device: /dev/spidev.0
#  SHM:
#    type: shm
#    params:
#      filename: leds

#  UDPOutput:
#    type: udp
#    params:
#      host: 172.23.97.109
#      port: 6453

#output: Websocket1
